# Generated by Django 4.0.2 on 2023-02-18 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_rename_email_contact_emails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='emails',
            new_name='email',
        ),
    ]
